/** @type {import('ts-jest').JestConfigWithTsJest} */

export default {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testPathIgnorePatterns: ['dist'],
  resolver: 'jest-ts-webcompat-resolver',
  moduleNameMapper: {
    '\\.(css|scss)$': 'identity-obj-proxy',
  },
  coveragePathIgnorePatterns: [
    'main.tsx',
    'src / main.tsx',
    'src / vite - env.d.ts',
    'src / services / local.storage.ts',
    'src / config.ts',
    'src / store / store.ts',
    'src / components / app / app.tsx',
    'src / services / images.ts',
    'src / pages / admin.panel / admin.panel.tsx',
    'src / pages / create.care / create.care.tsx',
    'src / components / about.us / about.us.tsx',
    'src / components / admin.panel / admin.panel.tsx',
    'src / services / cares / api.repo.cares.ts',
    'src / services / users / api.repo.users.ts',
    'src / components / app.routes / app.routes.tsx',
    'src / components / appointment / appointment.tsx',
    'src / pages / appointment / appointment.tsx',
    'src / components / card / card.tsx',
    'src / slices / cares / cares.slice.tsx',
    'src / slices / cares / cares.thunks.ts',
    'src / slices / users / users.thunk.ts',
    'src / slices / users / users.slice.tsx',
    'src / components / create.care / create.care.tsx',
    'src / components / footer / footer.tsx',
    'src / components / header / header.tsx',
    'src / pages / home / home.tsx',
    'src / components / layout / layout.tsx',
    'src / components / list / list.tsx',
    'src / components / login / login.tsx',
    'src / components / our.service / our.service.tsx',
    'src / components / register / register.tsx',
    'src / hooks / cares / use.cares.tsx',
    'src / components / user.buttons / user.buttons.tsx',
    'src / main.tsx',
  ],
};
